# Generated by Django 3.0.2 on 2020-02-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100, unique=True)),
                ('item_number', models.IntegerField()),
                ('item_text', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_text', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('parent_url', models.CharField(max_length=300)),
                ('period_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=1000)),
                ('subject_url', models.CharField(max_length=1000, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Period'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content_url', models.CharField(max_length=1000, unique=True)),
                ('content', models.TextField()),
                ('file_type', models.CharField(choices=[('HTML', 'HTML'), ('docx', 'docx'), ('pdf', 'pdf'), ('unknown', 'unknown')], default='HTML', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Subject')),
            ],
        ),
    ]
