# Generated by Django 3.0.4 on 2020-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='city',
            field=models.CharField(default='Zagreb', max_length=100),
        ),
    ]
