# Generated by Django 3.0.4 on 2020-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_period_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='city',
        ),
        migrations.AddField(
            model_name='act',
            name='city',
            field=models.CharField(default='Zagreb', max_length=100),
        ),
    ]
