# Generated by Django 3.0.2 on 2020-01-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('url', models.CharField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='skupstina.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('item_description', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('unit', models.CharField(max_length=300)),
                ('item_url', models.CharField(max_length=300)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skupstina.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=1000)),
                ('content_url', models.CharField(max_length=1000, unique=True)),
                ('content', models.TextField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skupstina.Item')),
            ],
        ),
    ]
