# Generated by Django 3.0.4 on 2020-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperperiod',
            name='url',
            field=models.CharField(default='initial', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
