# Generated by Django 3.0.4 on 2020-06-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_split', '0002_scraperperiod_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperperiod',
            name='date_text',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
