# Generated by Django 3.0.4 on 2021-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True)),
                ('date', models.DateTimeField()),
                ('period_text', models.CharField(max_length=100, null=True)),
                ('scrape_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
